"""Calibre xRC shared SVRF control-file generation."""

from __future__ import annotations

from pathlib import Path

from caddefaults import Defaults
from cadcalibre.defaults import calibre_defaults

from .config import DesignContext, RceConfig
from .gen_lvs import (
    append_custom_svrf,
    lvs_recognize_gates_line,
    lvs_virtual_connect_lines,
)
from .oa_view import write_calibreview_setup
from .textutil import clean_lines, q, write_text
from .xrc import build_xrc_plan
from .xrc_cells import write_xrc_cell_lists
from .xrc_models import XrcSettings
from .xrc_options import xrc_netlist_options, xrc_option_lines


def generate_xrc(cfg: RceConfig, ctx: DesignContext, *, defaults: Defaults | None = None) -> Path:
    baseline = calibre_defaults("calibre-xrc.svrf", defaults, ctx.log_dir)
    plan = build_xrc_plan(cfg, ctx)
    for settings in plan.settings:
        _generate_xrc_control(cfg, ctx, settings, baseline.get("default", []))
    return plan.settings[0].control_file


def _generate_xrc_control(
    cfg: RceConfig, ctx: DesignContext, settings: XrcSettings, baseline: list[str]
) -> Path:
    write_xrc_cell_lists(settings)
    netlist_options = " ".join(xrc_netlist_options(cfg, ctx, settings))
    netlist_statement = "PEX NETLIST SIMPLE" if settings.simple_netlist else "PEX NETLIST"
    lines = [
        "// Calibre xRC control file generated by rcepy.",
        f'LAYOUT PATH "{q(ctx.layout_path)}"',
        "LAYOUT SYSTEM GDSII",
        f'LAYOUT PRIMARY "{q(ctx.layout_cell)}"',
        "",
        f'SOURCE PATH "{q(ctx.source_path)}"',
        "SOURCE SYSTEM SPICE",
        f'SOURCE PRIMARY "{q(ctx.source_cell)}"',
        "",
        f'{netlist_statement} "{q(str(settings.output_file))}" {netlist_options}',
    ]
    if settings.character_map_line:
        lines.append(settings.character_map_line)
    if settings.pin_order_line:
        lines.append(settings.pin_order_line)
    lines.extend(
        [
            f'MASK SVDB DIRECTORY "{q(ctx.svdb_dir)}" QUERY XRC',
            f'LVS REPORT "{q(str(settings.lvs_report))}"',
            lvs_recognize_gates_line(cfg),
            *baseline,
        ]
    )
    lines.extend(
        xrc_option_lines(
            cfg,
            ctx,
            settings.temperature,
            simple_netlist=settings.simple_netlist,
        )
    )
    lines.extend(lvs_virtual_connect_lines(cfg))
    lines.extend(
        [
            "",
            f'INCLUDE "{q(str(settings.lvs_rule_file))}"',
            f'INCLUDE "{q(str(settings.rule_file))}"',
        ]
    )
    if cfg.lvs_case_sensitive():
        lines.extend(["SOURCE CASE YES", "LAYOUT CASE YES"])
    elif settings.netlist_format == "CALIBREVIEW":
        lines.append("SOURCE CASE YES")
    text = append_custom_svrf(clean_lines(lines), cfg)
    control_file = write_text(settings.control_file, text)
    if settings.netlist_format == "CALIBREVIEW":
        write_calibreview_setup(cfg, ctx, settings.output_file)
    return control_file
