"""Validate cellview artifacts generated by cdsTextTo5x."""

from __future__ import annotations

import hashlib
import os
import stat as stat_module
from pathlib import Path
from typing import List, Optional, Protocol, Tuple

from .errors import Nl2ViewError


class ImportTarget(Protocol):
    source: Path
    cell: str
    view: str
    copy_source: bool


ArtifactSnapshot = Tuple[
    Tuple[str, int, int, int, int, int, Optional[str], Optional[str]], ...
]


def view_snapshot(view_directory: Path) -> Optional[ArtifactSnapshot]:
    """Record enough metadata to detect a rewritten cellview."""

    if not view_directory.is_dir():
        return None
    entries: List[
        Tuple[str, int, int, int, int, int, Optional[str], Optional[str]]
    ] = []
    for entry in sorted(view_directory.rglob("*")):
        try:
            stat = entry.lstat()
        except FileNotFoundError:
            continue
        if stat_module.S_ISDIR(stat.st_mode):
            continue
        relative = str(entry.relative_to(view_directory))
        link_target = os.readlink(entry) if entry.is_symlink() else None
        digest = (
            _sample_digest(entry)[1] if stat_module.S_ISREG(stat.st_mode) else None
        )
        entries.append(
            (
                relative,
                stat.st_mode,
                stat.st_size,
                stat.st_mtime_ns,
                stat.st_ctime_ns,
                stat.st_ino,
                link_target,
                digest,
            )
        )
    return tuple(entries)


def master_file(view_directory: Path) -> Path:
    """Return the validated master file named by a text view's master.tag."""

    master_tag = view_directory / "master.tag"
    if not master_tag.is_file() or master_tag.stat().st_size == 0:
        raise Nl2ViewError(f"view has no master.tag: {view_directory}")
    names = [
        line.strip()
        for line in master_tag.read_text(
            encoding="utf-8", errors="replace"
        ).splitlines()
        if line.strip() and not line.lstrip().startswith("--")
    ]
    if len(names) != 1:
        raise Nl2ViewError(f"view has an invalid master.tag: {master_tag}")
    name = Path(names[0])
    if name.is_absolute() or len(name.parts) != 1 or name.name in {".", ".."}:
        raise Nl2ViewError(f"view has an unsafe master.tag: {master_tag}")
    master = view_directory / name
    if not master.is_file() or master.stat().st_size == 0:
        raise Nl2ViewError(f"view master file is missing or empty: {master}")
    return master


def _sample_digest(path: Path, sample_size: int = 64 * 1024) -> Tuple[int, str]:
    """Return a bounded content summary suitable for very large DSPF files."""

    size = path.stat().st_size
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        if size <= sample_size * 3:
            for chunk in iter(lambda: stream.read(1024 * 1024), b""):
                digest.update(chunk)
        else:
            offsets = (0, size // 2 - sample_size // 2, size - sample_size)
            for offset in offsets:
                stream.seek(offset)
                digest.update(offset.to_bytes(8, "big"))
                digest.update(stream.read(sample_size))
    return size, digest.hexdigest()


def _full_digest(path: Path) -> Tuple[int, str]:
    size = path.stat().st_size
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return size, digest.hexdigest()


def validate_imported_view(
    request: ImportTarget,
    library_path: Path,
    before: Optional[ArtifactSnapshot],
) -> None:
    """Require a complete OA text view and the requested copy/link behavior."""

    view_directory = library_path / request.cell / request.view
    if not view_directory.is_dir():
        raise Nl2ViewError(f"cdsTextTo5x did not create view: {view_directory}")
    master = master_file(view_directory)
    connectivity = view_directory / "netlist.oa"
    if not connectivity.is_file() or connectivity.stat().st_size == 0:
        raise Nl2ViewError(
            f"view has no OA connectivity database: {connectivity}"
        )
    if request.copy_source:
        if master.is_symlink():
            raise Nl2ViewError(f"copy mode created a linked master file: {master}")
        if _full_digest(master) != _full_digest(request.source):
            raise Nl2ViewError(
                f"view master does not match the input netlist: {master}"
            )
    else:
        try:
            linked_to_source = os.path.samefile(master, request.source)
        except OSError:
            linked_to_source = False
        if not linked_to_source:
            raise Nl2ViewError(
                f"link mode master does not refer to the input netlist: {master}"
            )
    after = view_snapshot(view_directory)
    if before is not None and after == before:
        raise Nl2ViewError(
            f"cdsTextTo5x did not update existing view: {view_directory}"
        )
