from __future__ import annotations

import os
import shutil
from pathlib import Path

import pytest
from form_lifecycle_fixtures import RUN_PROBE, _install_tree, _skill_literal
from skill_probe_support import run_virtuoso_source


@pytest.mark.skipif(
    not RUN_PROBE,
    reason="set RCE_RUN_SKILL_PROBE=1 to run the Virtuoso reduction-form probe",
)
def test_rce_reduction_form_tracks_output_capabilities(tmp_path: Path) -> None:
    virtuoso = shutil.which(os.environ.get("RCE_VIRTUOSO", "virtuoso"))
    if virtuoso is None:
        pytest.skip("virtuoso is unavailable")
    install = _install_tree(tmp_path)
    replay = tmp_path / "rce-reduction-form.il"
    log = tmp_path / "rce-reduction-form.log"
    replay.write_text(
        "\n".join(
            (
                f'setShellEnvVar("CAD_HOME" {_skill_literal(install)})',
                f'load({_skill_literal(install / "tools/rce/skill++/RCE.ils")})',
                'probeLib=ddCreateLib("rce_reduction_probe" '
                f'{_skill_literal(tmp_path / "rce_reduction_probe")})',
                'probeCv=dbOpenCellViewByType("rce_reduction_probe" "top" '
                '"layout" "maskLayout" "w")',
                "when(probeCv dbSave(probeCv) dbClose(probeCv))",
                "cadDisplayRceForm()",
                "form=rceForm",
                "startupGenerateOk=and(form~>createNetlistView~>enabled",
                "  !form~>createNetlistView~>invisible",
                "  !form~>createNetlistView~>value)",
                "form~>createNetlistView~>value=t",
                "generateOnlyOk=and(form~>createNetlistView~>value",
                "  !form~>reductionEnable~>value)",
                "form~>reductionEnable~>value=t",
                "rceReductionCB(form)",
                "bothEnabledOk=and(form~>createNetlistView~>enabled",
                "  form~>createNetlistView~>value",
                "  form~>reductionEnable~>enabled",
                "  form~>reductionEnable~>value)",
                "form~>createNetlistView~>value=nil",
                "reductionOnlyOk=and(!form~>createNetlistView~>value",
                "  form~>reductionEnable~>value)",
                "form~>reductionEnable~>value=nil",
                "rceReductionCB(form)",
                "bothDisabledOk=and(!form~>createNetlistView~>value",
                "  !form~>reductionEnable~>value)",
                "initialOk=and(form form~>reductionEnable form~>reductionMode",
                "  form~>reductionOutputTag form~>reductionControl",
                "  form~>reductionDelayRel form~>reductionDelayAbs",
                "  form~>reductionFrequency form~>reductionSelectionFile",
                "  form~>reductionTemperature form~>reductionGround",
                "  form~>reductionNegative form~>reductionCanonicalDeviceFile",
                "  !form~>reductionEnable~>value",
                "  form~>reductionOptions~>invisible",
                '  hiGetLayoutFrame(form \'reductionOptions)=="Reduction Options"',
                '  getq(form rceReductionFormVersion)=="20260909.pin.order.v1")',
                "modeLoc=hiGetGridLayoutItemLocation(form 'reductionMode)",
                "modePromptLoc=hiGetGridLayoutItemLocation(form 'reductionModePrompt)",
                "tagLoc=hiGetGridLayoutItemLocation(form 'reductionOutputTag)",
                "tagPromptLoc=hiGetGridLayoutItemLocation(form 'reductionOutputTagPrompt)",
                "controlLoc=hiGetGridLayoutItemLocation(form 'reductionControl)",
                "controlPromptLoc=hiGetGridLayoutItemLocation(form 'reductionControlPrompt)",
                "delayRelLoc=hiGetGridLayoutItemLocation(form 'reductionDelayRel)",
                "delayRelPromptLoc=hiGetGridLayoutItemLocation(form 'reductionDelayRelPrompt)",
                "delayAbsLoc=hiGetGridLayoutItemLocation(form 'reductionDelayAbs)",
                "delayAbsPromptLoc=hiGetGridLayoutItemLocation(form 'reductionDelayAbsPrompt)",
                "frequencyLoc=hiGetGridLayoutItemLocation(form 'reductionFrequency)",
                "frequencyPromptLoc=hiGetGridLayoutItemLocation(form 'reductionFrequencyPrompt)",
                "promptOk=and(modeLoc modePromptLoc tagLoc tagPromptLoc",
                "  controlLoc controlPromptLoc delayRelLoc",
                "  delayRelPromptLoc delayAbsLoc delayAbsPromptLoc",
                "  frequencyLoc frequencyPromptLoc",
                "  car(modeLoc)=='reductionOptions",
                "  caddr(modeLoc)==1 caddr(modePromptLoc)==0",
                "  caddr(tagLoc)==1 caddr(tagPromptLoc)==0",
                "  caddr(controlLoc)==1 caddr(controlPromptLoc)==0",
                "  car(delayRelLoc)=='reductionOptions",
                "  car(delayAbsLoc)=='reductionOptions",
                "  car(frequencyLoc)=='reductionOptions",
                "  cadr(delayRelLoc)==3",
                "  cadr(delayAbsLoc)==4",
                "  cadr(frequencyLoc)==5",
                "  caddr(delayRelLoc)==1 caddr(delayRelPromptLoc)==0",
                "  caddr(delayAbsLoc)==1 caddr(delayAbsPromptLoc)==0",
                "  caddr(frequencyLoc)==1 caddr(frequencyPromptLoc)==0)",
                "enableIndex=hiGetLayoutItemIndex(form 'reductionEnable)",
                "nativeViewIndex=hiGetLayoutItemIndex(form 'nativeViewLay)",
                "targetIndex=hiGetLayoutItemIndex(form 'viewTarget)",
                "reductionLayoutIndex=hiGetLayoutItemIndex(form 'reductionEnableLay)",
                "layoutOrderOk=and(nativeViewIndex reductionLayoutIndex",
                "  cadr(nativeViewIndex)<cadr(reductionLayoutIndex))",
                "targetOrderOk=and(targetIndex nativeViewIndex reductionLayoutIndex",
                "  car(targetIndex)=='nativeViewLay",
                "  car(nativeViewIndex)=='outLay",
                "  car(reductionLayoutIndex)=='outLay",
                "  cadr(nativeViewIndex)<cadr(reductionLayoutIndex))",
                "enableInfo=hiGetFieldInfo(form 'reductionEnable)",
                "createViewInfo=hiGetFieldInfo(form 'createNetlistView)",
                "enableAlignOk=and(enableInfo createViewInfo",
                "  car(car(enableInfo))==car(car(createViewInfo))",
                "  car(enableIndex)=='reductionEnableLay)",
                'form~>outType~>value="dspf"',
                'form~>inpType~>value="OA"',
                'form~>topCellSource~>value="Layout"',
                'form~>layLib~>value="rce_reduction_probe"',
                'form~>layCell~>value="top"',
                'form~>layView~>value="layout"',
                "rceInpCB(form)",
                "rceOutTypeCB(form)",
                "form~>createNetlistView~>value=t",
                "form~>reductionEnable~>value=t",
                "rceReductionCB(form)",
                # Non-OA native-view output has no implicit OA destination.
                # Both fields must be editable, and either field must keep the
                # complete lib/cell/view target synchronized.
                'form~>outType~>value="view"',
                "rceOutTypeCB(form)",
                'form~>inpType~>value="CDL+GDS"',
                "rceInpCB(form)",
                "savedMessageApp=getd('GUI_messageApp)",
                "putd('GUI_messageApp lambda((severity title message) t))",
                'form~>cdlRunDirectory~>value=""',
                "cdlDirectoryValidationOk=!rceValidateCdlRunDirectory(form)",
                "cdlDirectoryValidationOk=and(cdlDirectoryValidationOk",
                "  progn(rceRunCB(form) rceRunCloseCB(form) hiIsFormDisplayed(form)))",
                f'form~>cdlRunDirectory~>value={_skill_literal(tmp_path)}',
                "cdlDirectoryValidationOk=and(cdlDirectoryValidationOk",
                "  !rceValidateCdlRunDirectory(form))",
                f'cdlEnv=outfile({_skill_literal(tmp_path / "si.env")})',
                'fprintf(cdlEnv "simulator = auCdl\\n")',
                "close(cdlEnv)",
                "cdlDirectoryValidationOk=and(cdlDirectoryValidationOk",
                "  rceValidateCdlRunDirectory(form))",
                "putd('GUI_messageApp savedMessageApp)",
                "cdlDirectoryVisibilityOk=!form~>cdlRunDirectory~>invisible",
                "foreach(inputType '(\"CDL+GDS\" \"CDL+LAY\" \"SVDB\" \"CCI\")",
                "  form~>inpType~>value=inputType",
                "  rceSyncNativeView(form)",
                "  cdlDirectoryVisibilityOk=and(cdlDirectoryVisibilityOk",
                "    !form~>cdlRunDirectory~>invisible))",
                'form~>inpType~>value="OA"',
                "rceSyncNativeView(form)",
                "cdlDirectoryVisibilityOk=and(cdlDirectoryVisibilityOk",
                "  form~>cdlRunDirectory~>invisible)",
                'form~>inpType~>value="CDL+GDS"',
                'form~>extTool~>value="StarRC"',
                "rceSyncNativeView(form)",
                "cdlDirectoryVisibilityOk=and(cdlDirectoryVisibilityOk",
                "  form~>cdlRunDirectory~>invisible)",
                'form~>extTool~>value="QRC"',
                "rceSyncNativeView(form)",
                'form~>viewTarget~>value="results_lib/top/av_extracted"',
                "rceViewTargetCB(form)",
                "nonOATargetEditableOk=and(form~>viewTarget~>editable",
                "  form~>viewName~>editable form~>viewName~>enabled",
                '  form~>viewTarget~>value=="results_lib/top/av_extracted"',
                '  form~>viewName~>value=="av_extracted")',
                'form~>viewName~>value="smart_view_custom"',
                "rceViewNameCB(form)",
                "nonOANameEditOk=and(form~>viewName~>editable",
                '  form~>viewName~>value=="smart_view_custom"',
                '  form~>viewTarget~>value=="results_lib/top/smart_view_custom"',
                '  caddr(rceNativeViewTarget(form))=="smart_view_custom")',
                'form~>inpType~>value="OA"',
                "rceInpCB(form)",
                "oaTargetStateOk=and(!form~>viewTarget~>editable",
                "  form~>viewName~>editable form~>viewName~>enabled)",
                'form~>outType~>value="dspf"',
                "rceOutTypeCB(form)",
                # Returning from the native-view capability check should not
                # implicitly restore a cleared user choice; select it again
                # explicitly before testing reduction-mode transitions.
                "form~>createNetlistView~>value=t",
                "singleCornerOk=and(form~>reductionEnable~>enabled",
                "  form~>reductionEnable~>value",
                "  !form~>reductionOptions~>invisible)",
                'form~>cornerType~>value="Multiple Corners"',
                "rceCornerTypeCB(form)",
                "multiCornerOk=and(!form~>reductionEnable~>enabled",
                "  !form~>reductionEnable~>value",
                "  form~>reductionOptions~>invisible)",
                'form~>cornerType~>value="Single Corner"',
                "rceCornerTypeCB(form)",
                "restoredSingleCornerOk=and(form~>reductionEnable~>enabled",
                "  !form~>reductionEnable~>value",
                "  form~>reductionOptions~>invisible)",
                # Continue the capability checks with Reduction explicitly
                # re-enabled; returning to Single Corner must not restore the
                # checked state implicitly.
                "form~>reductionEnable~>value=t",
                "rceReductionCB(form)",
                "promptGeometryOk=and(form~>reductionModePrompt~>invisible==nil",
                "  form~>reductionOutputTagPrompt~>invisible==nil",
                "  form~>reductionControlPrompt~>invisible",
                "  form~>reductionDelayRelPrompt~>invisible",
                "  form~>reductionDelayAbsPrompt~>invisible",
                "  form~>reductionFrequencyPrompt~>invisible)",
                "defaultOk=and(form~>reductionEnable~>enabled==t",
                "  !form~>reductionOptions~>invisible",
                "  form~>reductionControl~>invisible",
                "  form~>reductionDelayRel~>invisible",
                "  form~>reductionDelayAbs~>invisible",
                "  form~>reductionFrequency~>invisible",
                "  form~>reductionSelectionFile~>invisible",
                "  !form~>reductionTemperature~>invisible",
                "  form~>reductionCanonicalDeviceFile~>invisible)",
                'form~>reductionMode~>value="Reduction Control"',
                "rceReductionModeCB(form)",
                "controlOk=and(!form~>reductionControl~>invisible",
                "  form~>reductionDelayRel~>invisible",
                "  form~>reductionDelayAbs~>invisible",
                "  form~>reductionFrequency~>invisible",
                "  form~>reductionSelectionFile~>invisible)",
                'form~>reductionMode~>value="Delay and Frequency"',
                "rceReductionModeCB(form)",
                "delayGeometryOk=and(!form~>reductionDelayRelPrompt~>invisible",
                "  !form~>reductionDelayAbsPrompt~>invisible",
                "  !form~>reductionFrequencyPrompt~>invisible)",
                "delayRelInfo=hiGetFieldInfo(form 'reductionDelayRel)",
                "delayAbsInfo=hiGetFieldInfo(form 'reductionDelayAbs)",
                "frequencyInfo=hiGetFieldInfo(form 'reductionFrequency)",
                "delayWidthsOk=and(delayRelInfo delayAbsInfo frequencyInfo",
                "  car(hiGetFieldMinSize(form 'reductionDelayRel))>=180",
                "  car(hiGetFieldMinSize(form 'reductionDelayAbs))>=180",
                "  car(hiGetFieldMinSize(form 'reductionFrequency))>=180)",
                "delayOk=and(!form~>reductionDelayRel~>invisible",
                "  !form~>reductionDelayAbs~>invisible",
                "  !form~>reductionFrequency~>invisible",
                "  form~>reductionControl~>invisible",
                "  form~>reductionSelectionFile~>invisible)",
                'form~>reductionMode~>value="Selection File"',
                "rceReductionModeCB(form)",
                "selectionOk=and(!form~>reductionSelectionFile~>invisible",
                "  form~>reductionControl~>invisible",
                "  form~>reductionDelayRel~>invisible",
                "  form~>reductionDelayAbs~>invisible",
                "  form~>reductionFrequency~>invisible)",
                "createViewModeCyclesOk=t",
                "for(cycle 1 20",
                "  foreach(mode list(\"Default\" \"Reduction Control\"",
                "                    \"Delay and Frequency\" \"Selection File\")",
                "    form~>reductionMode~>value=mode",
                "    rceReductionModeCB(form)",
                "    createViewModeCyclesOk=and(createViewModeCyclesOk",
                "      form~>createNetlistView~>enabled",
                "      !form~>createNetlistView~>invisible",
                "      form~>createNetlistView~>value)))",
                "createViewOutputCyclesOk=t",
                "for(cycle 1 20",
                "  foreach(outputType list(\"view\" \"sp\" \"dspf\")",
                "    form~>outType~>value=outputType",
                "    rceOutTypeCB(form)",
                "    when(member(outputType list(\"sp\" \"dspf\"))",
                "      createViewOutputCyclesOk=and(createViewOutputCyclesOk",
                "        form~>createNetlistView~>enabled",
                "        !form~>createNetlistView~>invisible))))",
                'form~>outType~>value="dspf"',
                "rceOutTypeCB(form)",
                "form~>createNetlistView~>value=t",
                'originalNetlists=list("/tmp/top.dspf")',
                'reducedNetlists=list("/tmp/top.reduced.dspf")',
                "dualRequest=rceNetlistViewRequest(",
                '  form list("rce_reduction_probe" "top" "top")',
                "  originalNetlists reducedNetlists \"dspf\")",
                "dualRequestOk=and(dualRequest car(dualRequest)==\"group\"",
                "  length(dualRequest)==3 car(cadr(dualRequest))==\"text\"",
                "  nth(3 cadr(dualRequest))==\"/tmp/top.dspf\"",
                "  nth(6 cadr(dualRequest))==nil",
                "  car(caddr(dualRequest))==\"text\"",
                "  nth(3 caddr(dualRequest))==\"/tmp/top.reduced.dspf\"",
                "  nth(6 caddr(dualRequest))==\"dspfText_reduced\"",
                "  rceSummaryViewTargetText(dualRequest)==strcat(",
                '    "rce_reduction_probe/top/dspfText, "',
                '    "rce_reduction_probe/top/dspfText_reduced"))',
                "batchDualRequest=rceBatchViewRequest(",
                "  form \"/tmp/run\" originalNetlists reducedNetlists \"dspf\")",
                "batchDualRequestOk=equal(batchDualRequest dualRequest)",
                "form~>reductionEnable~>value=nil",
                "rceReductionCB(form)",
                "originalRequest=rceNetlistViewRequest(",
                '  form list("rce_reduction_probe" "top" "top")',
                "  originalNetlists originalNetlists \"dspf\")",
                "originalRequestOk=and(originalRequest",
                "  car(originalRequest)==\"text\" length(originalRequest)==6",
                "  nth(3 originalRequest)==\"/tmp/top.dspf\")",
                "form~>reductionEnable~>value=t",
                "rceReductionCB(form)",
                'form~>reductionTemperature~>value="125"',
                'form~>outType~>value="sp"',
                "rceOutTypeCB(form)",
                'spiceOk=and(form~>reductionTemperature~>value==""',
                "  form~>reductionTemperature~>invisible",
                "  !form~>reductionCanonicalDeviceFile~>invisible)",
                'form~>reductionCanonicalDeviceFile~>value="canonical.dev"',
                'form~>outType~>value="dspf"',
                "rceOutTypeCB(form)",
                'dspfOk=and(form~>reductionCanonicalDeviceFile~>value==""',
                "  !form~>reductionTemperature~>invisible",
                "  form~>reductionCanonicalDeviceFile~>invisible)",
                'form~>outType~>value="view"',
                "rceOutTypeCB(form)",
                'form~>viewKind~>value="Smart View"',
                "rceViewKindCB(form)",
                "smartOk=and(form~>reductionEnable~>enabled==t",
                "  !form~>reductionTemperature~>invisible)",
                'form~>reductionTemperature~>value="85"',
                'form~>viewKind~>value="Extracted View"',
                "rceViewKindCB(form)",
                'extractedOk=and(form~>reductionTemperature~>value==""',
                "  form~>reductionTemperature~>invisible)",
                'form~>outType~>value="spef"',
                "rceOutTypeCB(form)",
                "unsupportedOk=and(!form~>reductionEnable~>enabled",
                "  !form~>reductionEnable~>value",
                "  form~>reductionOptions~>invisible)",
                "when(and(startupGenerateOk generateOnlyOk bothEnabledOk",
                "         nonOATargetEditableOk nonOANameEditOk oaTargetStateOk cdlDirectoryVisibilityOk cdlDirectoryValidationOk",
                "         reductionOnlyOk bothDisabledOk initialOk promptOk",
                "         promptGeometryOk delayGeometryOk",
                "         enableAlignOk layoutOrderOk targetOrderOk",
                "         defaultOk singleCornerOk multiCornerOk",
                "         restoredSingleCornerOk controlOk delayWidthsOk delayOk",
                "         selectionOk createViewModeCyclesOk createViewOutputCyclesOk",
                "         dualRequestOk batchDualRequestOk originalRequestOk",
                "         spiceOk dspfOk smartOk extractedOk unsupportedOk)",
                '  printf("RCE_REDUCTION_FORM_OK\\n"))',
                "when(form hiFormDone(form) hiDeleteForm(form))",
                "exit()",
                "",
            )
        ),
        encoding="utf-8",
    )
    output = run_virtuoso_source(replay.read_text(), tmp_path,
        env_updates={'RCE_DB_DIR': str(tmp_path), 'RCE_DEF_TOOL': 'QRC', 'RCE_OUTPUT_CHOICES': 'dspf,sp,view,spef'}, log_path=log)
    assert "*Error*" not in output
    assert "(reader)" not in output
    assert "Bad value" not in output
    assert "RCE_REDUCTION_FORM_OK" in output
