"""Legacy test collector; migrate callers to domain cases before removal."""


from rule_select_static_cases import (
    test_parse_rule_groups_handles_svrf_comments_continuations_and_order as test_parse_rule_groups_handles_svrf_comments_continuations_and_order,
    test_parse_rule_groups_handles_tvf_and_omits_unresolved_names as test_parse_rule_groups_handles_tvf_and_omits_unresolved_names,
    test_read_rule_groups_rejects_missing_rule_file as test_read_rule_groups_rejects_missing_rule_file,
    test_read_rule_groups_ignores_undecodable_bytes as test_read_rule_groups_ignores_undecodable_bytes,
    test_discover_rule_groups_uses_static_parser_for_plain_svrf as test_discover_rule_groups_uses_static_parser_for_plain_svrf,
    test_static_discovery_flattens_recursive_includes_in_run_directory_order as test_static_discovery_flattens_recursive_includes_in_run_directory_order,
    test_static_discovery_limits_aggregate_include_bytes as test_static_discovery_limits_aggregate_include_bytes,
    test_discover_rule_groups_counts_nested_wildcard_and_regex_members as test_discover_rule_groups_counts_nested_wildcard_and_regex_members,
    test_group_wildcard_treats_regex_metacharacters_as_literals as test_group_wildcard_treats_regex_metacharacters_as_literals,
)

from rule_select_cache_cases import (
    test_default_cache_dir_uses_current_working_directory as test_default_cache_dir_uses_current_working_directory,
    test_configured_cache_dir_still_overrides_current_working_directory as test_configured_cache_dir_still_overrides_current_working_directory,
    test_default_cache_dir_honors_frontend_temp_root_after_cwd_change as test_default_cache_dir_honors_frontend_temp_root_after_cwd_change,
    test_calibre_environment_restores_empty_original_library_path as test_calibre_environment_restores_empty_original_library_path,
    test_tvf_cache_invalidates_when_static_dependency_changes as test_tvf_cache_invalidates_when_static_dependency_changes,
    test_tvf_cache_skips_dynamic_tcl_dependency_substitutions as test_tvf_cache_skips_dynamic_tcl_dependency_substitutions,
)

from rule_select_expansion_cases import (
    test_discover_rule_groups_expands_tvf_and_caches_result as test_discover_rule_groups_expands_tvf_and_caches_result,
    test_svrf_discovers_tvf_include_after_large_plain_prefix as test_svrf_discovers_tvf_include_after_large_plain_prefix,
    test_discover_rule_groups_falls_back_when_calibre_fails as test_discover_rule_groups_falls_back_when_calibre_fails,
    test_discover_rule_groups_rejects_invalid_timeout as test_discover_rule_groups_rejects_invalid_timeout,
)
