"""Compatibility collector; case modules are not auto-discovered twice."""

from batch_controller_core_cases import test_parallel_tasks_persist_json_and_tsv as test_parallel_tasks_persist_json_and_tsv
from batch_controller_core_cases import test_task_environment_uses_batch_launch_cad_temp as test_task_environment_uses_batch_launch_cad_temp
from batch_controller_core_cases import test_failed_task_does_not_stop_remaining_tasks as test_failed_task_does_not_stop_remaining_tasks
from batch_controller_core_cases import test_cli_cancellation_marks_active_and_pending_tasks as test_cli_cancellation_marks_active_and_pending_tasks
from batch_controller_core_cases import test_manifest_rejects_duplicate_run_directories as test_manifest_rejects_duplicate_run_directories
from batch_controller_core_cases import test_publication_finalize_updates_waiting_task as test_publication_finalize_updates_waiting_task
from batch_controller_core_cases import test_publication_finalize_preserves_canceled_tasks as test_publication_finalize_preserves_canceled_tasks
from batch_process_control_cases import test_cancel_command_failure_still_terminates_process_group as test_cancel_command_failure_still_terminates_process_group
from batch_process_control_cases import test_cancel_command_uses_batch_launch_cad_environment as test_cancel_command_uses_batch_launch_cad_environment
