"""Compatibility collector for nl2view source acceptance.

Case modules use ``*_cases.py`` names so normal test discovery executes each
case once. Retire this collector after test commands migrate to those modules.
"""

from nl2view_cli_cases import test_format_mapping_and_default_copy_mode as test_format_mapping_and_default_copy_mode
from nl2view_cli_cases import test_import_can_run_from_gui_worker_thread as test_import_can_run_from_gui_worker_thread
from nl2view_cli_cases import test_link_mode_customizes_optional_view_arguments as test_link_mode_customizes_optional_view_arguments
from nl2view_cli_cases import test_copy_mode_replaces_existing_link_to_same_source as test_copy_mode_replaces_existing_link_to_same_source
from nl2view_cli_cases import test_defaults_cds_library_file_from_working_directory as test_defaults_cds_library_file_from_working_directory
from nl2view_cli_cases import test_requires_explicit_cell_before_starting_cadence as test_requires_explicit_cell_before_starting_cadence
from nl2view_cli_cases import test_rejects_pspice_before_starting_cadence as test_rejects_pspice_before_starting_cadence
from nl2view_cli_cases import test_accepts_generic_spice_as_hspice_compatible_input as test_accepts_generic_spice_as_hspice_compatible_input
from nl2view_cli_cases import test_validates_inputs_before_starting_cadence as test_validates_inputs_before_starting_cadence
from nl2view_cli_cases import test_preserves_cadence_exit_code_and_diagnostics as test_preserves_cadence_exit_code_and_diagnostics
from nl2view_process_cases import test_term_stops_importer_and_its_descendants as test_term_stops_importer_and_its_descendants
from nl2view_process_cases import test_term_is_forwarded_to_importer_process_group as test_term_is_forwarded_to_importer_process_group
from nl2view_process_cases import test_restores_eda_library_path_for_cadence_child as test_restores_eda_library_path_for_cadence_child
from nl2view_process_cases import test_restores_mts_netlistor_eda_library_path_for_cadence_child as test_restores_mts_netlistor_eda_library_path_for_cadence_child
from nl2view_process_cases import test_does_not_restore_other_flow_library_paths as test_does_not_restore_other_flow_library_paths
from nl2view_process_cases import test_cadence_child_does_not_inherit_python_or_linker_injection as test_cadence_child_does_not_inherit_python_or_linker_injection
from nl2view_process_cases import test_direct_cds_lib_debug_resolution_detaches_mps_environment as test_direct_cds_lib_debug_resolution_detaches_mps_environment
from nl2view_diagnostics_cases import test_rejects_cadence_error_diagnostic_with_zero_exit as test_rejects_cadence_error_diagnostic_with_zero_exit
from nl2view_diagnostics_cases import test_ignores_missing_optional_aivivc_gdm_after_successful_import as test_ignores_missing_optional_aivivc_gdm_after_successful_import
from nl2view_diagnostics_cases import test_still_rejects_unrelated_gdm_error_after_successful_import as test_still_rejects_unrelated_gdm_error_after_successful_import
from nl2view_resolver_cases import test_does_not_ignore_generic_gdm_contact_error_without_plugin_marker as test_does_not_ignore_generic_gdm_contact_error_without_plugin_marker
from nl2view_resolver_cases import test_rejects_zero_exit_without_a_created_view as test_rejects_zero_exit_without_a_created_view
from nl2view_resolver_cases import test_rejects_undefined_library_without_modifying_cds_lib as test_rejects_undefined_library_without_modifying_cds_lib
from nl2view_resolver_cases import test_resolves_included_library_relative_to_included_file as test_resolves_included_library_relative_to_included_file
from nl2view_resolver_cases import test_uses_cadence_resolver_for_installation_root_expressions as test_uses_cadence_resolver_for_installation_root_expressions
from nl2view_resolver_cases import test_finds_cadence_resolver_from_explicit_install_bin as test_finds_cadence_resolver_from_explicit_install_bin
from nl2view_resolver_cases import test_finds_cadence_resolver_from_share_dfii_entry as test_finds_cadence_resolver_from_share_dfii_entry
from nl2view_resolver_cases import test_rejects_library_mapping_that_differs_from_active_session as test_rejects_library_mapping_that_differs_from_active_session
from nl2view_resolver_cases import test_accepts_library_mapping_that_matches_active_session as test_accepts_library_mapping_that_matches_active_session
from nl2view_resolver_cases import test_installation_root_expression_requires_cadence_resolver as test_installation_root_expression_requires_cadence_resolver
from nl2view_resolver_cases import test_cds_lib_keeps_hash_in_library_path as test_cds_lib_keeps_hash_in_library_path
from nl2view_resolver_cases import test_cds_lib_accepts_double_dash_comment as test_cds_lib_accepts_double_dash_comment
from nl2view_resolver_cases import test_cds_lib_ignores_unresolved_soft_entries as test_cds_lib_ignores_unresolved_soft_entries
from nl2view_resolver_cases import test_cds_lib_invalid_redefinition_preserves_existing_library as test_cds_lib_invalid_redefinition_preserves_existing_library
from nl2view_artifacts_cases import test_cds_lib_undefine_overrides_included_library as test_cds_lib_undefine_overrides_included_library
from nl2view_artifacts_cases import test_overwrites_existing_view_even_with_same_second_timestamps as test_overwrites_existing_view_even_with_same_second_timestamps
from nl2view_artifacts_cases import test_detects_same_size_content_change_with_preserved_timestamps as test_detects_same_size_content_change_with_preserved_timestamps
from nl2view_artifacts_cases import test_reports_missing_cds_text_to_5x_before_subprocess_start as test_reports_missing_cds_text_to_5x_before_subprocess_start
from nl2view_artifacts_cases import test_reports_cds_lib_debug_start_failure_as_resolver_error as test_reports_cds_lib_debug_start_failure_as_resolver_error
from nl2view_artifacts_cases import test_uses_configured_sico_temp_directory as test_uses_configured_sico_temp_directory
from nl2view_artifacts_cases import test_rejects_unknown_library_before_starting_cadence as test_rejects_unknown_library_before_starting_cadence
from nl2view_artifacts_cases import test_executes_resolved_tilde_program_path as test_executes_resolved_tilde_program_path
