"""Compatibility collector for cadview manager cases.

Non-discoverable *_cases.py modules keep normal discovery free of duplicates.
Retire this entry when supported test commands migrate to the case modules.
"""

from cadview_manager_core_cases import test_manager_loads_filesystem_provider_with_diagnostics as test_manager_loads_filesystem_provider_with_diagnostics
from cadview_manager_core_cases import test_manager_rejects_missing_and_unknown_inputs as test_manager_rejects_missing_and_unknown_inputs
from cadview_manager_core_cases import test_manager_custom_provider_is_qt_free_and_preserves_result as test_manager_custom_provider_is_qt_free_and_preserves_result
from cadview_manager_core_cases import test_custom_provider_receives_only_supported_complete_context as test_custom_provider_receives_only_supported_complete_context
from cadview_manager_core_cases import test_manager_forwards_output_callback_to_supporting_provider as test_manager_forwards_output_callback_to_supporting_provider
from cadview_manager_core_cases import test_positional_only_provider_parameters_are_not_passed_as_keywords as test_positional_only_provider_parameters_are_not_passed_as_keywords
from cadview_manager_core_cases import test_provider_type_error_is_not_hidden_by_a_retry as test_provider_type_error_is_not_hidden_by_a_retry
from cadview_manager_core_cases import test_callable_provider_and_public_registration as test_callable_provider_and_public_registration
from cadview_manager_core_cases import test_register_provider_validates_input_and_closed_state as test_register_provider_validates_input_and_closed_state
from cadview_manager_core_cases import test_constructor_validates_custom_providers as test_constructor_validates_custom_providers
from cadview_manager_concurrency_cases import test_submit_returns_request_and_supersedes_older_request as test_submit_returns_request_and_supersedes_older_request
from cadview_manager_concurrency_cases import test_completed_request_is_not_marked_cancelled_by_later_submission as test_completed_request_is_not_marked_cancelled_by_later_submission
from cadview_manager_concurrency_cases import test_close_wait_false_can_be_followed_by_wait_true as test_close_wait_false_can_be_followed_by_wait_true
from cadview_manager_concurrency_cases import test_concurrent_submit_cannot_escape_latest_request_cancellation as test_concurrent_submit_cannot_escape_latest_request_cancellation
from cadview_manager_concurrency_cases import test_cancel_cannot_miss_a_request_during_submit_registration as test_cancel_cannot_miss_a_request_during_submit_registration
from cadview_manager_concurrency_cases import test_cancel_event_is_honored_before_provider_invocation as test_cancel_event_is_honored_before_provider_invocation
from cadview_manager_concurrency_cases import test_close_is_idempotent_and_rejects_new_submissions as test_close_is_idempotent_and_rejects_new_submissions
