#!/usr/bin/env python3
"""Generate SKILL menu data from cad/utility/menu.toml."""

from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib
except ImportError:  # pragma: no cover - Python 3.9 runtime
    import tomli as tomllib


def skill_string(value: object) -> str:
    text = "" if value is None else str(value)
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def skill_bool(value: object) -> str:
    return "t" if bool(value) else "nil"


def skill_list(items: list[str]) -> str:
    return "list(" + " ".join(skill_string(item) for item in items) + ")"


def item_expr(item: dict[str, object]) -> str:
    name = item.get("name", item.get("text", ""))
    return (
        "list("
        f"{skill_string(name)} "
        f"{skill_string(item.get('text', ''))} "
        f"{skill_string(item.get('callback', ''))} "
        f"{skill_bool(item.get('enabled', True))}"
        ")"
    )


def section_expr(data: dict[str, object], name: str) -> str:
    section = data.get(name, {})
    if not isinstance(section, dict):
        section = {}
    items = section.get("items", [])
    if not isinstance(items, list):
        items = []
    view_types = section.get("view_types", [])
    if not isinstance(view_types, list):
        view_types = []
    return (
        "list("
        f"{skill_bool(section.get('enabled', True))} "
        f"{skill_string(section.get('title', ''))} "
        f"{skill_list([str(item) for item in view_types])} "
        "list("
        + " ".join(item_expr(item) for item in items if isinstance(item, dict))
        + ")"
        ")"
    )


def generate(config_path: Path, output_path: Path) -> None:
    with config_path.open("rb") as handle:
        data = tomllib.load(handle)
    settings = data.get("settings", {})
    if not isinstance(settings, dict):
        settings = {}
    text = "\n".join(
        [
            "; Generated by menu_to_skill.py. Edit menu.toml instead.",
            f"witMenuLogoEnv={skill_string(settings.get('logo_env', 'LOGO'))}",
            f"witMenuDefaultLogo={skill_string(settings.get('default_logo', 'SiCo'))}",
            f"witMenuCIW={section_expr(data, 'ciw')}",
            f"witMenuLayout={section_expr(data, 'layout')}",
            f"witMenuSchematic={section_expr(data, 'schematic')}",
            "",
        ]
    )
    if output_path.is_file() and output_path.read_text(encoding="utf-8") == text:
        return
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(text, encoding="utf-8")


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: menu_to_skill.py /path/menu.toml /path/menu.generated.il", file=sys.stderr)
        return 2
    try:
        generate(
            Path(argv[1]).expanduser().resolve(),
            Path(argv[2]).expanduser().resolve(),
        )
    except OSError as exc:
        print(f"menu generation failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
