"""Legacy collector; remove when test scripts use domain case modules."""

from publication_preflight_cases import (
    test_publish_rejects_library_not_bound_to_current_session,
    test_publish_rejects_session_target_path_change,
    test_existing_view_is_rejected_before_importer,
    test_symbol_and_text_existing_destinations_are_checked_independently,
)

from publication_text_cases import (
    test_rename_top_netlist_changes_only_top_declaration_and_terminator,
    test_spectre_language_marker_helper_is_idempotent,
    test_target_overlay_and_environment_do_not_leak_source_selector,
    test_text_overwrite_is_allowed_only_with_text_checkbox_and_reports_replacement,
    test_successful_fake_import_receives_renamed_request_and_target_environment,
    test_same_cell_spectre_publish_stages_marker_even_for_scs_source,
)

from publication_bundle_cases import (
    test_bundle_preflight_rejects_either_existing_view_before_symbol_or_text_mutation,
    test_bundle_reports_manual_cleanup_when_symbol_succeeded_before_text_failure,
    test_bundle_reports_manual_cleanup_for_partial_text_view,
    test_manual_cleanup_result_contains_operator_diagnostics_and_evidence_paths,
)

from publication_ownership_cases import (
    test_spectre_staging_adds_language_marker_without_rewriting_stable_artifact,
    test_failed_import_does_not_delete_artifacts_created_by_importer,
    test_strict_publication_accepts_only_manifested_success_artifact,
    test_strict_publication_allows_target_selected_after_generation,
    test_strict_publication_rejects_tampered_manifested_artifact,
    test_public_validate_run_artifact_accepts_path_like_inputs,
)

__all__ = ['test_publish_rejects_library_not_bound_to_current_session', 'test_publish_rejects_session_target_path_change', 'test_existing_view_is_rejected_before_importer', 'test_symbol_and_text_existing_destinations_are_checked_independently', 'test_rename_top_netlist_changes_only_top_declaration_and_terminator', 'test_spectre_language_marker_helper_is_idempotent', 'test_target_overlay_and_environment_do_not_leak_source_selector', 'test_text_overwrite_is_allowed_only_with_text_checkbox_and_reports_replacement', 'test_successful_fake_import_receives_renamed_request_and_target_environment', 'test_same_cell_spectre_publish_stages_marker_even_for_scs_source', 'test_bundle_preflight_rejects_either_existing_view_before_symbol_or_text_mutation', 'test_bundle_reports_manual_cleanup_when_symbol_succeeded_before_text_failure', 'test_bundle_reports_manual_cleanup_for_partial_text_view', 'test_manual_cleanup_result_contains_operator_diagnostics_and_evidence_paths', 'test_spectre_staging_adds_language_marker_without_rewriting_stable_artifact', 'test_failed_import_does_not_delete_artifacts_created_by_importer', 'test_strict_publication_accepts_only_manifested_success_artifact', 'test_strict_publication_allows_target_selected_after_generation', 'test_strict_publication_rejects_tampered_manifested_artifact', 'test_public_validate_run_artifact_accepts_path_like_inputs']
