"""Legacy collector; remove after scripts migrate to GUI domain cases."""

from gui_window_fixtures import application

from gui_log_cases import (
    test_gui_worker_logs_are_marshaled_and_filtered,
    test_gui_streams_safe_catalog_startup_output_and_redacts_protocol,
    test_gui_drains_filtered_worker_logs_on_poll,
    test_source_catalog_diagnostics_are_rendered_without_cache_key_dump,
    test_gui_expands_manual_cleanup_publication_diagnostics,
    test_repeated_publication_state_is_logged_once,
)

from gui_result_cases import (
    test_single_cell_generation_populates_and_enables_open_result,
    test_multicell_generation_keeps_ordered_result_rows,
    test_publication_views_are_attached_to_the_matching_cell,
    test_new_run_and_invalidation_clear_result_browser_state,
    test_open_result_view_requires_current_session_library,
)

from gui_defaults_values_cases import (
    test_gui_applies_typed_defaults_without_changing_publication_state,
    test_gui_normalizes_nested_gmin_from_raw_defaults_report,
    test_defaults_report_missing_fields_preserves_existing_process_values,
    test_legacy_defaults_probe_helper_uses_selected_cell_dialect,
)

from gui_defaults_revision_cases import (
    test_gui_discards_defaults_after_requesting_cell_changes,
    test_gui_applies_defaults_to_requesting_cell_after_user_browses_another_cell,
    test_gui_preserves_requesting_cell_edits_when_defaults_return_late,
    test_automatic_defaults_use_dialect_revision_and_not_other_dialect_edit,
)

from gui_defaults_queue_cases import (
    test_select_source_view_queues_defaults_probe_and_preserves_advanced_options,
    test_automatic_defaults_waits_behind_controller_operation,
    test_cancel_defaults_probe_restores_process_cursor,
    test_defaults_busy_cursor_is_scoped_to_its_process_tab,
    test_defaults_probes_selected_cells_serially,
    test_deleting_active_defaults_cell_cancels_only_that_probe,
)

from gui_defaults_dialect_cases import (
    test_select_source_view_prefetches_both_simulators_and_switch_uses_cache,
)

from gui_layout_cases import (
    test_process_tabs_host_plain_pages_without_their_own_title_bar,
    test_source_lists_and_resizable_splitters,
    test_selected_cell_titles_the_right_side_settings_frame,
    test_logger_splitter_can_allocate_height_in_both_directions,
    test_group_frames_commands_and_overwrite_columns_align,
    test_simulator_form_only_exposes_requested_process_controls,
    test_multicell_layout_and_model_file_double_click_contract,
)

from gui_table_cases import (
    test_gui_collects_process_and_advanced_options,
    test_gui_rejects_invalid_advanced_option_via_shared_validator,
    test_temperature_and_scale_keep_user_text_until_request_validation,
    test_model_file_corner_combo_parses_and_maps_to_section,
    test_model_file_double_click_scans_selected_file_once,
    test_removing_model_or_advanced_option_invalidates_generation,
    test_hidden_legacy_process_controls_invalidate_generation,
)

from gui_process_tab_cases import (
    test_process_tabs_use_new_process_placeholder_and_isolate_state,
    test_process_tab_close_button_removes_page_and_renumbers,
    test_host_session_replacement_updates_all_page_controllers,
    test_run_all_processes_tabs_in_order,
    test_cancel_all_cancels_every_page_in_batch_snapshot,
)

from gui_source_selection_cases import (
    test_multicell_source_queue_copies_and_restores_per_cell_settings,
    test_combined_source_view_queues_physical_member_identity,
    test_deleting_active_and_last_source_cell_loads_or_clears_form,
    test_new_source_cell_copies_simulation_settings_not_publication,
)

from gui_workspace_io_cases import (
    test_gui_config_round_trip_preserves_startup_and_simrc,
    test_gui_workspace_config_round_trip_replaces_all_process_tabs,
    test_host_save_config_writes_all_process_tabs_to_one_workspace_file,
    test_workspace_save_load_preserves_raw_process_field_text,
    test_gui_workspace_invalid_load_keeps_existing_tabs,
    test_loading_config_preserves_unknown_target_and_invalidates_old_generation,
)

from gui_workspace_transaction_cases import (
    test_workspace_replace_shuts_down_page_that_fails_during_apply,
    test_workspace_replace_contains_post_commit_catalog_refresh_error,
)

from gui_source_catalog_cases import (
    test_repeated_controller_state_keeps_selected_source_for_publish,
    test_source_refresh_defers_target_refresh_until_source_is_displayed,
    test_explicit_source_refresh_bypasses_cache_but_project_restore_reuses_it,
    test_explicit_source_refresh_preserves_legacy_manual_controller_signature,
    test_source_cdslib_switch_clears_old_queue_and_worker_context,
    test_delayed_source_catalog_for_old_cdslib_is_ignored,
)

from gui_source_guard_cases import (
    test_source_cds_lib_guard_rejects_current_session_file_before_refresh,
    test_source_cds_lib_guard_catches_symlink_alias_in_browse,
    test_source_cds_lib_guard_rejects_loaded_config_before_mutating_form,
)

from gui_project_cases import (
    test_project_selector_uses_isolated_source_environment,
    test_failed_project_change_restores_previous_project_context,
)

from gui_generation_identity_cases import (
    test_publish_reuses_successful_generation_source_identity,
    test_generate_request_excludes_late_publication_selection,
    test_consumed_generation_is_not_resurrected_by_catalog_state,
    test_stale_single_generation_is_not_displayed_after_source_switch,
    test_netlist_input_edits_invalidate_generation_but_publication_edits_do_not,
    test_publish_rejects_netlist_input_digest_drift,
)

from gui_publication_handoff_cases import (
    test_run_without_publication_only_starts_generation,
    test_run_freezes_publication_and_continues_after_generation,
    test_run_cancel_before_queued_publication_does_not_publish,
)

from gui_publication_target_cases import (
    test_gui_overwrite_controls_are_independent_and_follow_generate_toggles,
    test_run_multicell_publication_checks_all_queued_cells,
    test_run_rejects_unknown_target_library_before_generation,
)

__all__ = ['application', 'test_gui_worker_logs_are_marshaled_and_filtered', 'test_gui_streams_safe_catalog_startup_output_and_redacts_protocol', 'test_gui_drains_filtered_worker_logs_on_poll', 'test_source_catalog_diagnostics_are_rendered_without_cache_key_dump', 'test_gui_expands_manual_cleanup_publication_diagnostics', 'test_repeated_publication_state_is_logged_once', 'test_single_cell_generation_populates_and_enables_open_result', 'test_multicell_generation_keeps_ordered_result_rows', 'test_publication_views_are_attached_to_the_matching_cell', 'test_new_run_and_invalidation_clear_result_browser_state', 'test_open_result_view_requires_current_session_library', 'test_gui_applies_typed_defaults_without_changing_publication_state', 'test_gui_normalizes_nested_gmin_from_raw_defaults_report', 'test_defaults_report_missing_fields_preserves_existing_process_values', 'test_legacy_defaults_probe_helper_uses_selected_cell_dialect', 'test_gui_discards_defaults_after_requesting_cell_changes', 'test_gui_applies_defaults_to_requesting_cell_after_user_browses_another_cell', 'test_gui_preserves_requesting_cell_edits_when_defaults_return_late', 'test_automatic_defaults_use_dialect_revision_and_not_other_dialect_edit', 'test_select_source_view_queues_defaults_probe_and_preserves_advanced_options', 'test_automatic_defaults_waits_behind_controller_operation', 'test_cancel_defaults_probe_restores_process_cursor', 'test_defaults_busy_cursor_is_scoped_to_its_process_tab', 'test_defaults_probes_selected_cells_serially', 'test_deleting_active_defaults_cell_cancels_only_that_probe', 'test_select_source_view_prefetches_both_simulators_and_switch_uses_cache', 'test_source_lists_and_resizable_splitters', 'test_selected_cell_titles_the_right_side_settings_frame', 'test_logger_splitter_can_allocate_height_in_both_directions', 'test_group_frames_commands_and_overwrite_columns_align', 'test_simulator_form_only_exposes_requested_process_controls', 'test_multicell_layout_and_model_file_double_click_contract', 'test_gui_collects_process_and_advanced_options', 'test_gui_rejects_invalid_advanced_option_via_shared_validator', 'test_temperature_and_scale_keep_user_text_until_request_validation', 'test_model_file_corner_combo_parses_and_maps_to_section', 'test_model_file_double_click_scans_selected_file_once', 'test_removing_model_or_advanced_option_invalidates_generation', 'test_hidden_legacy_process_controls_invalidate_generation', 'test_process_tabs_use_new_process_placeholder_and_isolate_state', 'test_process_tab_close_button_removes_page_and_renumbers', 'test_host_session_replacement_updates_all_page_controllers', 'test_run_all_processes_tabs_in_order', 'test_cancel_all_cancels_every_page_in_batch_snapshot', 'test_multicell_source_queue_copies_and_restores_per_cell_settings', 'test_combined_source_view_queues_physical_member_identity', 'test_deleting_active_and_last_source_cell_loads_or_clears_form', 'test_new_source_cell_copies_simulation_settings_not_publication', 'test_gui_config_round_trip_preserves_startup_and_simrc', 'test_gui_workspace_config_round_trip_replaces_all_process_tabs', 'test_host_save_config_writes_all_process_tabs_to_one_workspace_file', 'test_workspace_save_load_preserves_raw_process_field_text', 'test_gui_workspace_invalid_load_keeps_existing_tabs', 'test_loading_config_preserves_unknown_target_and_invalidates_old_generation', 'test_workspace_replace_shuts_down_page_that_fails_during_apply', 'test_workspace_replace_contains_post_commit_catalog_refresh_error', 'test_repeated_controller_state_keeps_selected_source_for_publish', 'test_source_refresh_defers_target_refresh_until_source_is_displayed', 'test_explicit_source_refresh_bypasses_cache_but_project_restore_reuses_it', 'test_explicit_source_refresh_preserves_legacy_manual_controller_signature', 'test_source_cdslib_switch_clears_old_queue_and_worker_context', 'test_delayed_source_catalog_for_old_cdslib_is_ignored', 'test_source_cds_lib_guard_rejects_current_session_file_before_refresh', 'test_source_cds_lib_guard_catches_symlink_alias_in_browse', 'test_source_cds_lib_guard_rejects_loaded_config_before_mutating_form', 'test_project_selector_uses_isolated_source_environment', 'test_failed_project_change_restores_previous_project_context', 'test_publish_reuses_successful_generation_source_identity', 'test_generate_request_excludes_late_publication_selection', 'test_consumed_generation_is_not_resurrected_by_catalog_state', 'test_stale_single_generation_is_not_displayed_after_source_switch', 'test_netlist_input_edits_invalidate_generation_but_publication_edits_do_not', 'test_publish_rejects_netlist_input_digest_drift', 'test_run_without_publication_only_starts_generation', 'test_run_freezes_publication_and_continues_after_generation', 'test_run_cancel_before_queued_publication_does_not_publish', 'test_gui_overwrite_controls_are_independent_and_follow_generate_toggles', 'test_run_multicell_publication_checks_all_queued_cells', 'test_run_rejects_unknown_target_library_before_generation']
