"""Stable vocabulary, identity patterns and limits for the AIVW protocol."""

from __future__ import annotations

from enum import Enum
import re


PROTOCOL_VERSION = "aivw-agent-v1"


MAX_ID_LENGTH = 160


MAX_MESSAGE_BYTES = 4 * 1024 * 1024


MAX_JSONL_RECORDS = 4096


IDENTIFIER_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:/-]{0,159}$")


GENERATION_PATTERN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:/+@=-]{0,255}$")


MAX_BUDGET_VALUE = 1_000_000_000


class ActionKind(str, Enum):
    PLAN_EXPERIMENT = "PLAN_EXPERIMENT"
    SUBMIT_EXPERIMENT = "SUBMIT_EXPERIMENT"
    PROPOSE_MODEL = "PROPOSE_MODEL"
    REQUEST_REVISION = "REQUEST_REVISION"
    FINISH = "FINISH"
    BLOCKED = "BLOCKED"


ACTION_KINDS = frozenset(item.value for item in ActionKind)


class ErrorCode(str, Enum):
    INVALID_ENVELOPE = "INVALID_ENVELOPE"
    UNKNOWN_FIELD = "UNKNOWN_FIELD"
    INVALID_ACTION = "INVALID_ACTION"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"
    DUPLICATE_ACTION = "DUPLICATE_ACTION"
    STALE_SOURCE_GENERATION = "STALE_SOURCE_GENERATION"
    TEMPLATE_LOCK_MISMATCH = "TEMPLATE_LOCK_MISMATCH"
    TOOL_NOT_ALLOWED = "TOOL_NOT_ALLOWED"
    TOOL_NOT_FOUND = "TOOL_NOT_FOUND"
    TOOL_SCHEMA_INVALID = "TOOL_SCHEMA_INVALID"
    PATH_DENIED = "PATH_DENIED"
    PATH_ESCAPE = "PATH_ESCAPE"
    SYMLINK_ESCAPE = "SYMLINK_ESCAPE"
    ENVIRONMENT_DENIED = "ENVIRONMENT_DENIED"
    CONTEXT_LIMIT_EXCEEDED = "CONTEXT_LIMIT_EXCEEDED"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    PROVIDER_UNAVAILABLE = "PROVIDER_UNAVAILABLE"
    MODEL_PROVIDER_UNAVAILABLE = "MODEL_PROVIDER_UNAVAILABLE"
    PROVIDER_TIMEOUT = "PROVIDER_TIMEOUT"
    PROVIDER_DISCONNECTED = "PROVIDER_DISCONNECTED"
    UNKNOWN_PROVIDER_STATE = "UNKNOWN_PROVIDER_STATE"
    UNKNOWN_SIDE_EFFECT = "UNKNOWN_SIDE_EFFECT"
    INTERRUPTED = "INTERRUPTED"
    INVALID_STATE = "INVALID_STATE"
    CHECKPOINT_INVALID = "CHECKPOINT_INVALID"
    BUNDLE_INVALID = "BUNDLE_INVALID"
    BUNDLE_HASH_MISMATCH = "BUNDLE_HASH_MISMATCH"
    BUNDLE_PROTOCOL_MISMATCH = "BUNDLE_PROTOCOL_MISMATCH"
    BUNDLE_SOURCE_MISMATCH = "BUNDLE_SOURCE_MISMATCH"
    BUNDLE_TEMPLATE_MISMATCH = "BUNDLE_TEMPLATE_MISMATCH"
    DETERMINISTIC_GATE_REQUIRED = "DETERMINISTIC_GATE_REQUIRED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class EventType(str, Enum):
    SESSION_STARTED = "session.started"
    SESSION_RESUMED = "session.resumed"
    TURN_STARTED = "turn.started"
    CONTEXT_BUILT = "context.built"
    ACTION_RECEIVED = "action.received"
    ACTION_REPLAYED = "action.replayed"
    TOOL_STARTED = "tool.started"
    TOOL_COMPLETED = "tool.completed"
    TOOL_FAILED = "tool.failed"
    CHECKPOINT_SAVED = "checkpoint.saved"
    TURN_COMPLETED = "turn.completed"
    SESSION_COMPLETED = "session.completed"
    INTERRUPTED = "session.interrupted"
    ERROR = "error"
    PROVIDER_UNAVAILABLE = "provider.unavailable"
    UNKNOWN_SIDE_EFFECT = "unknown_side_effect"
    GATE_EVALUATED = "gate.evaluated"
