"""Publish sourced document facts as a new, checked full-package revision."""

from copy import deepcopy
from pathlib import Path
import os
import shutil
import tempfile
import uuid

from ..pdk_normalize import now
from .jsonio import Writer, atomic, encode, fail, mapping, read, relative, TARGET
from .package import MAP_FIELDS, SUFFIX_FIELDS, Package, locked


def documents(package):
    """Return logical documents only; physical shards are regenerated by Writer."""
    return {name: package.document(name) for name in set(package.manifest['files']) | set(getattr(package, 'changes', {}))
            if name in MAP_FIELDS and name != 'package.json'
            or '/' in name and Path(name).name in SUFFIX_FIELDS}


def _authority(before, after):
    old_sources = before['sources.json']['items']
    if set(old_sources) - set(after['sources.json']['items']):
        fail('Document ingestion cannot remove existing provenance')
    for key, source in after['sources.json']['items'].items():
        if key in old_sources and source != old_sources[key]:
            fail('Document ingestion cannot rewrite existing provenance')
        if key not in old_sources and source['kind'] == 'user':
            fail('Use the interactive update workflow for user confirmation')
    if set(before['device.json']['items']) != set(after['device.json']['items']):
        fail('Device inventory changes require recollection')
    for key, row in after['device.json']['items'].items():
        old = before['device.json']['items'].get(key)
        if any(row.get(field) != old.get(field) for field in ('library', 'cell', 'view', 'dir')):
            fail('Document ingestion cannot change observed device identity')
        if old is None or row['use'] != old['use']:
            fail('Document ingestion cannot grant or change cell usage')
    for name, value in after.items():
        if not name.endswith('/cdf.json'):
            continue
        if value.get('interface_parameters') != before.get(name, {}).get('interface_parameters'):
            fail('Use the interactive update workflow for CDF interface scope')
        old = before.get(name, {}).get('parameters', {})
        if set(value['parameters']) != set(old):
            fail('CDF inventory changes require recollection')
        for key, row in value['parameters'].items():
            if key not in old or any(row[field] != old[key][field] for field in ('write', 'requirement')):
                fail('Use the interactive update workflow for CDF policies')


def write_documents(stage, manifest, content):
    writer = Writer(stage)
    for name, value in sorted(content.items()):
        fields = MAP_FIELDS.get(name, SUFFIX_FIELDS.get(Path(name).name, ()))
        writer.put(name, value, (*fields, 'evidence'))
    logical_manifest = dict(manifest)
    for field in ('libraries', 'dependencies'):
        if len(encode(manifest[field])) > TARGET:
            manifest[field] = writer.shard('package.json', field, manifest[field])
    inventory = dict(writer.files)
    if 'publication' in manifest:
        from .publication import content_digest
        manifest['publication']['content_digest'] = content_digest({**logical_manifest, 'files': inventory})
    manifest['files'] = writer.shard('package.json', 'files', inventory, inventory=False) if len(
        encode(inventory)) > TARGET else inventory
    writer.put('package.json', manifest, inventory=False)
    Package(stage).verify()


def publish(root, base, replacements, *, metadata=None, dependencies=None):
    """Atomically enrich the exact installed baseline; never replace an overlay.

    Inputs are reviewed logical documents with explicit sources, not executable
    extraction rules. Existing documents and source identities remain authoritative.
    Interactive permissions belong exclusively to Updates.
    """
    root = Path(root)
    base.verify()
    before = documents(base)
    content = {**before, **deepcopy(replacements)}
    _authority(before, content)
    metadata = metadata or {}
    if set(metadata) - {'pdk_version', 'options'}:
        fail('Unsupported collection metadata override')
    manifest = deepcopy(base.manifest)
    from .publication import invalidate
    invalidate(manifest)
    manifest.update(metadata)
    for key, value in (dependencies or {}).items():
        if key in manifest['dependencies'] and manifest['dependencies'][key] != value:
            fail('Changed source dependency requires recollection: ' + key)
        manifest['dependencies'][key] = value
    manifest.update(revision=uuid.uuid4().hex, created_at=now())
    with locked(root):
        index = read(root / 'index.json')
        index['packages'] = mapping(root, index['packages'])
        selected = []
        for key, entry in index['packages'].items():
            current = read(relative(root, entry['path']) / 'package.json')
            if current.get('base', {}).get('package_id') == manifest['package_id']:
                fail('Document enrichment requires explicit overlay rebase', 'pdk_update_conflict')
            if current.get('package_id') == manifest['package_id']:
                installed = Package(relative(root, entry['path']))
                if installed.manifest_digest != base.manifest_digest:
                    fail('Collection baseline changed', 'pdk_update_conflict')
                selected.append(key)
        if len(selected) != 1:
            fail('Exact installed baseline required', 'pdk_update_conflict')
        stage = Path(tempfile.mkdtemp(prefix='.documents-', dir=root))
        try:
            write_documents(stage, manifest, content)
            destination = manifest['package_id'] + '.' + manifest['revision'][:12]
            os.rename(stage, root / destination)
            index['packages'][selected[0]]['path'] = destination
            if len(encode(index['packages'])) > TARGET:
                index['packages'] = Writer(root).shard('index.' + manifest['revision'] + '.json',
                                                       'packages', index['packages'])
            atomic(root / 'index.json', index)
        finally:
            if stage.exists():
                shutil.rmtree(stage)
    return Package(root / destination)
