# Current configure values are authoritative; retired names only diagnose migration.
macro(sico_option current retired)
    if(NOT DEFINED ${current} AND DEFINED ENV{${current}})
        set(${current} "$ENV{${current}}" CACHE STRING "SiCo configure input")
    endif()
    if(NOT DEFINED ${current} AND (DEFINED ${retired} OR DEFINED ENV{${retired}}))
        message(FATAL_ERROR "${retired} was removed after SiCo v0.0.1; set ${current}")
    endif()
    if(DEFINED ${current})
        set(ENV{${current}} "${${current}}")
    endif()
    unset(${retired} CACHE)
    unset(${retired})
    unset(ENV{${retired}})
endmacro()

sico_option(SICO_AI_CODEX_EXECUTABLE CAD_AI_CODEX_EXECUTABLE)
sico_option(SICO_AI_DEVELOPMENT_STAGE CAD_AI_DEVELOPMENT_STAGE)
sico_option(SICO_AI_ICU_LICENSE_DIR CAD_AI_ICU_LICENSE_DIR)
sico_option(SICO_AI_ICU_RUNTIME_SONAMES CAD_AI_ICU_RUNTIME_SONAMES)
sico_option(SICO_AI_NATIVE_ENTRY_DIR CAD_AI_NATIVE_ENTRY_DIR)
sico_option(SICO_AI_NATIVE_PYTHON_DIR CAD_AI_NATIVE_PYTHON_DIR)
sico_option(SICO_AI_QT5_LICENSE_DIR CAD_AI_QT5_LICENSE_DIR)
sico_option(SICO_AI_QT5_ROOT CAD_AI_QT5_ROOT)
sico_option(SICO_AI_QT5_RUNTIME_PLUGINS CAD_AI_QT5_RUNTIME_PLUGINS)
sico_option(SICO_AI_QT5_X11EXTRAS_LICENSE_DIR CAD_AI_QT5_X11EXTRAS_LICENSE_DIR)
sico_option(SICO_AI_QTERMWIDGET_PYTHON_MODULE CAD_AI_QTERMWIDGET_PYTHON_MODULE)
sico_option(SICO_AI_QTERMWIDGET_ROOT CAD_AI_QTERMWIDGET_ROOT)
sico_option(SICO_AI_RHEL7_DEPS_ROOT CAD_AI_RHEL7_DEPS_ROOT)
sico_option(SICO_AI_RHEL7_GCC_ROOT CAD_AI_RHEL7_GCC_ROOT)
sico_option(SICO_AI_RHEL7_QT_ROOT CAD_AI_RHEL7_QT_ROOT)
sico_option(SICO_AI_RHEL8_GCC_ROOT CAD_AI_RHEL8_GCC_ROOT)
sico_option(SICO_AI_RHEL8_QT_ROOT CAD_AI_RHEL8_QT_ROOT)
sico_option(SICO_AI_SKILL_CONTEXT CAD_AI_SKILL_CONTEXT)
sico_option(SICO_PDK_WORKER_CONTEXT CAD_PDK_WORKER_CONTEXT)
